language: node_js
sudo: required
before_install:
  - npm install -g npm
  - npm --version
script:
  - npm run build
node_js:
  - '8'
deploy:
  provider: npm
  email: 'sargsyan.sargis.89@gmail.com'
  api_key: 'bdccdaa9-bc6d-481e-832b-92a94f620bf0'
  skip_cleanup: true
  on:
    tags: true
